name: Github Pages Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.12.0]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      # - run: npm ci
      - name: Install and build
        working-directory: ./app

        run: |
            npm install && npm run gh-build
            pwd
            ls
            
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: app/dist/portfolio # The folder the action should deploy.   